name: test7

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master ]

jobs:
  test7:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: boot
        shell: pwsh
        run: ./Invoke-Build.ps1 boot
      - name: test
        shell: pwsh
        run: ./Invoke-Build.ps1 . Tests/.build.ps1
