name: test2

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: boot
        shell: powershell
        run: ./Invoke-Build.ps1 boot
      - name: test
        shell: cmd
        run: powershell -Version 2 ./Invoke-Build.ps1 . Tests/.build.ps1
